databases:
  - name: budget_manager
    databaseName: budget_manager
    user: mysite

services:
  - type: web
    name: budget_manager
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_manager
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
